### ISSUE TITLE
bug: `useContractReads` aborts upon first read error

### ISSUE THREAD

**Issue by 0xVesper** [wevm/wagmi#1154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.6.7

### Current Behavior

Hello,

I've tried adding an `onError` to each read of `useContractReads`, but I don't believe the feature exists.

Is there a way to retrieve the error from each read, instead of aborting and only getting the first error returned?

Thank you 🤝

### Expected Behavior

`useContractreads` only will use `onError` if `allowFailure: false` and aborts all of the reads upon a single error. I need the reads to happen for each call passed in, and return an error for each call that happens if it exists.

### Steps To Reproduce

For example:

```
const { data, isError, isLoading } = useContractReads({
    contracts: [
      {
        ...wagmigotchiContract,
        functionName: 'getAlive',
        onError(error) {       // this does nothing since feature doesn't exist
               console.log("Error thrown: ", error);
        },
      },
    ],
  })
```

It currently forces use of `allowFailure`, will stop calling the reads after the first error is thrown, and only show said first error: 

```
const { data, isError, isLoading } = useContractReads({
    contracts: [
      {
        ...wagmigotchiContract,
        functionName: 'getAlive'
      },
    allowFailure: false,
    onError(error) {     // only works on first read error and stops all reads
      console.log("Error thrown: ", error);
    },
    ],
  })
```

**Comment by jxom** [comment]
Thanks for this issue!

Definitely agree it would be nice to have a way to extract the error of a contract read when `allowFailure` is truthy.

The way `onError` behaves right now is that it is invoked when the hook's function throws an error, but in this case, it will not as `allowFailure` is truthy. Perhaps we should have another option to handle this, like `onReadError` or something.

I'd say this issue is more of a feature request than a bug, so I am going to move this to a discussion under "Ideas" & I'll add it to the wagmi roadmap.
