### ISSUE TITLE
bug: wagmi read hooks send way too many requests

### ISSUE THREAD

**Issue by Amirjab21** [wevm/wagmi#2130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

0.11

### Current Behavior

It refetches the read hooks every second and this causes the react app to re-render which can cause flashing return values.

Is there a way to set a timer to determine when it should refetch?

### Expected Behavior

There should be a way to set a timer to determine how often it should refetch.

### Steps To Reproduce

Use any of the useContractRead hooks on any React page and this occurs.

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

Please provide some more info (e.g. are you using `watch: true`? `pollingInterval: 1_000`? what network are you using?).
