### ISSUE TITLE
bug: ChainID not found

### ISSUE THREAD

**Issue by Sneh1999** [wevm/wagmi#3346]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package Version

1.4.12

### Current Behavior

<img width="948" alt="image" src="https://github.com/wevm/wagmi/assets/35871990/58d1f1f4-bc12-44dd-8cc9-83d332b3f49a">

Seems like when Wagmi is calling `WalletConnect`, `WalletConnect` is not able to find the ChainID. 
I am using RainbowKit (https://www.rainbowkit.com/docs/installation)

### Expected Behavior

Should not throw this error and should be able to detect the ChainID

### Steps To Reproduce

You can follow the steps in docs for Rainbokit: https://www.rainbowkit.com/docs/installation

Or follow the run steps for my app here: https://github.com/Sneh1999/zk-capture-the-flag

### Link to Minimal Reproducible Example (StackBlitz, CodeSandbox, GitHub repo etc.)

https://github.com/Sneh1999/zk-capture-the-flag

**Comment by glitch-txs** [comment]
Were you able to reproduce this without RainbowKit? Only Wagmi?
Also keep in mind some mobile wallets do not support testnets.

**Comment by Sneh1999** [comment]
> Were you able to reproduce this without RainbowKit? Only Wagmi? Also keep in mind some mobile wallets do not support testnets.

Haven’t tried without rainbowkit but the error seems to originate from wagmi calling WC’s universal provider. It’s the most vanilla rainbowkit setup basically straight from the docs.

And yes I know certain mobile wallets don’t support WC but I’m not even trying to use a mobile wallet right now. This shows up on first load of the app each time, before I even attempt to connect a wallet. For what it’s worth, I’m using MetaMask after.

**Comment by glitch-txs** [comment]
I remember this error now, was MetaMask the only wallet used? and iOS or Android?

- I cloned your repo, works fine on my end, tried MetaMask on android and no errors.
- Try clearing localStorage and cache, this will make it work. Something broke on storage, this usually was happing with some wallets not supporting the current WalletConnect configuration but should be fixed by now, so probably there's a wallet that's causing this?

**Comment by glitch-txs** [comment]
I was able to reproduce the error with Rainbow wallet.
Rainbow will throw an error and WalletConnect is not properly handling it, when there're only chains that are not supported by Rainbow, so if you add mainnet (or any other supported chain) in the array this will prevent the error.
Feel free to close the issue here, this can be raised in [WalletConnect's monorepo](https://github.com/WalletConnect/walletconnect-monorepo).

**Comment by Sneh1999** [comment]
> I was able to reproduce the error with Rainbow wallet. Rainbow will throw an error and WalletConnect is not properly handling it, when there're only chains that are not supported by Rainbow, so if you add mainnet (or any other supported chain) in the array this will prevent the error. Feel free to close the issue here, this can be raised in [WalletConnect's monorepo](https://github.com/WalletConnect/walletconnect-monorepo).

I’ll try clearing cache and storage and report back in the morning, but I don’t think networks is the issue since the only chain I’m using is sepolia nothing else.

**Comment by glitch-txs** [comment]
Mmm, did you used any other wallet? I wasn't able to repro other way

**Comment by Sneh1999** [comment]
Okay, seems like it was a cache issue. Thanks @glitch-txs  for helping here, going to close the issue :)
