### ISSUE TITLE
Metamask showing when not on connectors

### ISSUE THREAD

**Issue by c0rdeiro** [wevm/wagmi#3393]
### Describe the bug

Metamask always shows even when it is not defined on connectors (example here https://stackblitz.com/edit/new-wagmi-aon6zk)
This happens when the browser has the extension, I tried with an incognito with no extensions and it works has it should
So my guess is that injected is always being loaded, even if the `injected()` is not on the connectors

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-aon6zk

### Wagmi Version

2.0.3

### Viem Version

2.0.2

### TypeScript Version

5.2.2

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by glitch-txs** [comment]
This is [EIP-6963](https://eips.ethereum.org/EIPS/eip-6963) which will detect the wallets that you have installed and create a connector for each of them. This is better than the injected connector because it avoids conflicts when you have multiple wallets installed.

However if you'd like to disable it you can do it with this flag: https://wagmi.sh/react/api/createConfig#multiinjectedproviderdiscovery

**Comment by c0rdeiro** [comment]
But that way we might have duplicate connectors, for example if I define metamask in connectors and user has the metamask extension. How can this be avoided? only by disabling with that flag?

**Comment by tmm** [comment]
Could try something like this https://github.com/wevm/wagmi/discussions/3068#discussioncomment-8032468

Closing this issue right now as it's not an issue.
