### ISSUE TITLE
`ChainNotConfiguredError: Chain not configured` Thrown when Changing Config Chains

### ISSUE THREAD

**Issue by frankfka** [wevm/wagmi#3425]
### Describe the bug

Our app has different deploy environments, where we configure chains depending on testnet/mainnet/etc.

With the latest `wagmi` update, we've found that `ChainNotConfiguredError: Chain not configured` is thrown when switching between configurations - I assume this is because there's some caching done at the localstorage level and re-initializing the app with a different config (that doesn't include the previous cached chain) will throw the error

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-ddy6bs?file=src%2Fwagmi.ts

### Steps To Reproduce

The stackblitz is configured for `mainnet`. Run the app, then change the configuration to only use `arbitrum` - the error should occur

### Wagmi Version

2.1.1

### Viem Version

2.0.6

### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

**Comment by 0xdino** [comment]
Example of a good config:

```ts
import { createConfig, http } from 'wagmi'
import { Chain, mainnet, sepolia } from 'wagmi/chains'
import { createClient } from 'viem'

export const chains: Chain[] = [mainnet, sepolia];

const config = createConfig({
  chains: [chains[0], ...chains.slice(1)],
  client({ chain }) {
    return createClient({ chain, transport: http() })
  },
})
```

But if the user switches the chain to an unknown chain, then the last connected network is returned by useChainId, it would be better to return the default one - chains[0]

**Comment by ramyjaiem** [comment]
getting the same issue when switching to another chain
we switch chain before connecting the user so my solution was adding `localStorage.removeItem('wagmi.store')` before changing the chain

**Comment by firnprotocol** [comment]
@ramyjaiem interesting, i can confirm that this actually "worked" to "resolve" the issue on my end (of course it's a workaround). thanks.

**Comment by firnprotocol** [comment]
btw, i noticed another thing. i _only_ got this error in localhost. on the other hand, i test _multiple_ apps in localhost, not just the one above (i.e., that for which the error was encountered). i wonder if there was some kind of pollution / cross-contamination of the local state, which was caused by two different apps being on the same address (namely, `http://localhost:8080`). so in other words this isn't "really" an issue i need to care about, since it was only triggered in unrepresentative conditions (two different dapps at same address).

**Comment by Yuripetusko** [comment]
I get this error when switching between 2 different projects on same localhost. Because wagmi config is saved in localStorage, so if first projects has [maiinet, polygon] as configured chains and second one has [base, sepolia], then when switching to the second one and trying to read something from base would throw the error, because localStorage still have chains from the fist project 🤔 Have to manually clear storage in this case

**Comment by tmm** [comment]
You can also set a unique storage [`key`](https://wagmi.sh/react/api/createStorage#key) for each project.
