### ISSUE TITLE
Vue composable promises

### ISSUE THREAD

**Issue by kleinpetr** [wevm/wagmi#3945]
### What is the type of issue?

Documentation is confusing

### What is the issue?

Hi,

I am not sure about the usage of the Vue composables, since there are no Promises so I can't await for the response :thinking: 

### Where did you find it?

https://wagmi.sh/vue/api/composables/useReadContract

**Comment by tmm** [comment]
You don't need to as the composables are reactive. Check out the [TanStack Query docs](https://tanstack.com/query/latest/docs/framework/vue/overview).

**Comment by kleinpetr** [comment]
@tmm in the template for sure, but inside custom composables / stores you have to use something like `until` to await until the variable has changed, which is not so convenient, is there any reason to use TanStack which is imho quite overhead and brings lot of complexity under the hood especially with SSR.

**Comment by jxom** [comment]
What are you trying to do?

**Comment by tmm** [comment]
Without knowing what you are trying to do, you might want to check out the [core actions](https://wagmi.sh/vue/api/actions), which you can import via the `'@wagmi/vue/actions'` entrypoint. We use TanStack because it has a performant, consistent API, works with SSR, is a surprisingly simple codebase to navigate, etc.
