### ISSUE TITLE
Connect action return type conflicts with ConnectReturnType

### ISSUE THREAD

**Issue by nbran** [wevm/wagmi#4048]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

The shape of the [resolved object](https://github.com/wevm/wagmi/blob/ee9d90d61ad76d3e2d165fbf07e6715c8f77616b/packages/core/src/connectors/createConnector.ts#L46) returned by the [connect action](https://wagmi.sh/core/api/actions/connect):

```typescript
connect(
      parameters?:
        | { chainId?: number | undefined; isReconnecting?: boolean | undefined }
        | undefined,
    ): Promise<{
      accounts: readonly Address[]
      chainId: number
    }>
```

Does not seem to be compatible with the [return type](https://github.com/wevm/wagmi/blob/ee9d90d61ad76d3e2d165fbf07e6715c8f77616b/packages/core/src/actions/connect.ts#L23) that is [outlined in the documentation](https://wagmi.sh/core/api/actions/connect#return-type):

```typescript
export type ConnectReturnType<config extends Config = Config> = {
  accounts: readonly [Address, ...Address[]]
  chainId:
    | config['chains'][number]['id']
    | (number extends config['chains'][number]['id'] ? number : number & {})
}
```
Specifically, the accounts object for the former implies that the Address array may be empty (`Address[]`), however, the accounts object in the latter implies at least one Address (`[Address, ...Address[]]`) must be present since there is one element before the spread operator.

I wondered if `ConnectReturnType` is specific to the return type for the [createConnector](https://wagmi.sh/core/api/createConnector) function and thus not relevant to the connect action, but this is the type argument used for the [Connector](https://github.com/wevm/wagmi/blob/ee9d90d61ad76d3e2d165fbf07e6715c8f77616b/packages/core/src/createConfig.ts#L542) interface definition, making it the return type for `connect` whenever handling a `Connector` object.

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

2.10.2

### Viem Version

2.13.10

### TypeScript Version

5.4.5

**Comment by tmm** [comment]
The difference between the two types is mostly practical as it makes building connectors easier. The `connect` action has a more specific type, the connector `connect` method is more general so there isn't a need to cast a bunch of internal types.

**Comment by nbran** [comment]
[Check out this example](https://stackblitz.com/edit/new-wagmi-5gdjpk?file=src%2FApp.tsx) and the comments in lines 25-29.

The issue is that the type for the accounts (array of addresses) as defined in `ConnectReturnType` is not quite compatible with the array returned by the `useConnect` hook or the connector's `connect` method. It might as well be a minor nuisance, but makes room for some confusion in an otherwise neatly typed library.

**Comment by tmm** [comment]
All the Wagmi-related types work fine for me in this [TypeScript Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC+cAZlBCHAORTo4DGMVAsAFCiSyJwDCEAdv3SNoAGhQY+g4THFp0AEWCp6AoYyKlylKgHccAcxDAW7cNHhIp6mACV0MZFH4AVAJ5gCxMhWr6jwAD0DDDAAqimHBbcAIIAJnG0qKiaPjoAbsDoIKZsqvyo8ADaIcDp6PGJ6MnV4hgwMYxlFQlJGKgAunAAvBJYuPgAPIVQwPwGRR0AfAAUkwCUeeHFpeUA6jgANpsOdQ6NoetbOzBdvfLYeOjDMKPjs1RUi6z5hdz5NtCo4h8ymueSNQyGbPV6WOBxZS-DTEAGKKFAxggthsEjIfhNAQQiCYCgOAAWYwMM2hdmqkAK6AAXLxEWTHM53J55og2HA4K8IDsAHSbCDEqgAUQAHp5GOg4nAYB4CMoaUVKm1xNyVYrqqhJh0qD86fZUBSMM9CCjWGiMaEsXEcXiYITxoLNhgSbryeFqXBaDgrfxNm44GrkgtWax2ZyeXyBSKxfhJdLPHA5f7WurJtqOS79W6jSazZj+OnpIwNtsHCSadYZNAWQg2QWbDNa+ykKToDT6ERRI3g+ye3BAoE4FGZBKPQ4nPm4+78TAYGBUFT+-5jNzUPjAp7GMEwEF8RAIABrVCBeQVxgAYloDP4AFpJ132QJMMh6PR1TSZnE8DgWd0pt3ez2-b+owyBbKOV5SjKCYpPwEDwAAjsgwD4FK+IEKgOAgOg4i3MABgGOgdwGHALiYHA+jOES3L3j2Vq4lhtpEh+X4skBGz8DAKQCAQAZcVAcAgNA6A0eydE2naBgOk6n64NyDCqOinGsQO7GcXAABehEQEmVTJHA0ACUJIlwPUBzNLx1TMbJ8kQIpqDPABPamU0RwljAJLckhcQOQBhCdiGPZ+bW2asKi6J5hCCKFjAxYnGWtLRVW-6QiodINgFTZ1pWUBth2XY1hlPaPs+r7JO+P5-gVjnss5hwtLp7RzB0PmObVzSxaWjwtYF-m9kFAUhUAA). The only type that doesn't work well is the user-defined type `string[]` since `` `0x${string}` `` is not equal to `string`.

**Comment by nbran** [comment]
Cleaned up the example in [TypeScript Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgVwM4FMDKMCGN1wC+cAZlBCHAORTo4DGMVAsAFCiSyJwDCEAdv3SNoAGhQY+g4THFp0AEWCp6AoYyKlylKgHccAcxDAW7cNHhIp6mACV0MZFH4AVAJ5gCxMhWr6jwAD0DDDAAqimHBbcAIIAJnG0qKiaPjoAbsDoIKZsqvyo8ADaIcDp6PGJ6MnV4hgwMYxlFQlJGKgAunAAvBJYuPgAPIVQwPwGRR0AfAAUkwCUeeHFpeUA6jgANpsOdQ6NoetbOzBdvfLYeOjDMKPjs1RUi6z5hdz5NtCo4h8ymueSNQyGbPV6WOBxZS-DTEAGKKFAxggthsEjIfhNAQQiCYCgOAAWYwMM2hdmqkAK6AAXLxEWTHM53J4ilQGKp0TAIh15og2HA4K8IDsAHSbCDEqgAUQAHp5GOg4nAYB4CMoaUVKm1xMKdZrqqhJh0qD86fZUBSMM9CCjWGiMaEsXEcXiYITxpLNhgSabyeFqXBaDgnfxNm44Hrkgteax+YKRWKJTK5fhFcrPHA1eHWvrJsaBT7zX6rTacKg3BjSOjMfx89JGBttg4STTrDJoDyEHzazYZl3+UhSdAafQiKI+9H+ZO4IFAnAkzIFQGHE4a2n-fiYDAwKgqTP-MZhah8YFA4xgmAgviIBAANaoQLyVuMADEtAZ-AAtGvx-yBJhkPQ9D6jSpbliOMxxHgOAtj675MugPLdFME5TpOM7howyBbEu75KiqGYpPwEDwAAjsgwD4Eq+IEKgOAgOg4i3MABgGOgdwGHALiYHA+jOESwo-pOTq4vRrpEhBUHCmyEAcqgPLoRs-CcnAAgEBGKTQHAIDQOggn8sJLpugYHpepBuBSYBMlKXJ06zopykAF5sRAWZVMkKlQFpOl6bWbykgcYT8GaYA9HAOD6BRArCqSyIxqh+nOqJRnenWDTVsFFnstZ8wANw+QZSVEiZ6ApTYAUCBl0myblPnofUAXlOp1QSeZVXZT59VNEcjYwCSwrkXEzzxYQY5xfyI1dsWrColWDo1pCKh0g2JzNrSqXtihC0xeOA50kOAqjjtgl-gBQHJDSII9MhnZjahnWHC0bntHM3IdfsXXoMtTaPENqETbd-38lNQA) - It should now highlight the difference in the `accounts` type provided by the hook and the action.

**Comment by nbran** [comment]
Disregard - I suppose this simply underscores [this point](https://github.com/wevm/wagmi/issues/4048#issuecomment-2165935431), although I still think it would be helpful to consolidate these two into a single type.
