### ISSUE TITLE
[BUG]: isConnected is incorrect

### ISSUE THREAD

**Issue by Pszz** [wevm/wagmi#4050]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

```ts
import { useAccount } from 'wagmi'
const { status, isConnected } = useAccount()
```

// Currently: it is true when status is the following, which is not quite right.
`"connected" | "reconnecting" | "connecting"`

isConnected should be true when status === 'connected'
Otherwise it should be false

### What Wagmi package(s) are you using?

wagmi

### Wagmi Version

"wagmi": "^2.9.8"

### Viem Version

"viem": "2.x"

### TypeScript Version

"typescript": "5.0.4",

**Comment by tmm** [comment]
This is the correct behavior:

- `status === 'connected'` — `isConnected` is `true` because account is connected
- `status === 'connecting'` — `isConnected` is `false` because account is not connected
- `status === 'reconnecting'` — `isConnected` is `boolean` because account might be connected

[TypeScript Playground](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAbzgVwM4FMCCBjbFkB28AvnAGZQQhwDkA7gIYDmIwNAsAFBd4GrxJ+DGGgA0cYKgDCEAgXTYY6ACZxSAXhQYceQjAAUASi5dgZOPqEjUcdXdq95ilTWOc4E6bKdLlXDwD0AXAAegD8XOgANhgS5pYwwmi29gBEjgowwARMqW4ekjJymSr+cEGhEZzRsWYWVsl2mqlQCt6Z2bn5nkU+pe7lweFAA)

```ts
import { useAccount } from 'wagmi'

const { status, isConnected } = useAccount()

if (status === 'connected')
  isConnected
  // ^? const isConnected: true
else if (status === "connecting")
  isConnected
  // ^? const isConnected: false
else if (status === "reconnecting")
  isConnected
  // ^? const isConnected: boolean
```

**Comment by Pszz** [comment]
```tsx
  const {  status, isConnected } = useAccount()
  const { signMessageAsync } = useSignMessage()
```

- status === 'reconnecting' — isConnected is boolean
^ This should not be `isConnected`

```tsx

useEffect(() => {

 if(isConnected){
    // **There will be an error here because there is no wallet connected.**
   signMessageAsync()  
 }

}, [isConnected])


```

**Comment by tmm** [comment]
> There will be an error here because there is no wallet connected.

The wallet could still be reconnecting since `isConnected` can be `true`.
