### ISSUE TITLE
`mock` Connector Results in `undefined` result from `useWalletClient`

### ISSUE THREAD

**Issue by frankfka** [wevm/wagmi#4317]
### Check existing issues

- [X] I checked there isn't [already an issue](https://github.com/wevm/wagmi/issues) for the bug I encountered.

### Describe the bug

I'm currently experimenting with `mock` connector to establish a "fake" connection within our app. I've found that:
- `useWalletClient` result is undefined, but I expect some mock signer to be returned instead
- `reconnect: true` does not result in a reconnection after refreshing the page

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/new-wagmi-f3azfv?file=src%2FApp.tsx

### Steps To Reproduce

See the stackblitz

### What Wagmi package(s) are you using?

wagmi

### Wagmi Package(s) Version(s)

2.10.10

### Viem Version

2.17.4

**Comment by tmm** [comment]
Interesting point. The intent of [`mock#features#reconnect`](https://wagmi.sh/react/api/connectors/mock#reconnect) is to enable support for the `mock` connector to reconnect, but does not guarantee that is reconnects as it relies on the in-memory `connected` flag for that.

The way to make sure the `mock` connector reconnects is to call the `connect` action before mounting or accessing config values. There are a couple examples of that in this commit https://github.com/wevm/wagmi/commit/7afb3f7f4c699c407b030597a05ac71060d5b754

Can consider changing this behavior in the future, but would likely be a breaking change due to the internal side effect changing.

**Comment by frankfka** [comment]
@tmm The usecase for the mock connector for us is to create a "connected" state in our app with an arbitrary address. How would you recommend we do this outside of a test environment?

**Comment by tmm** [comment]
Added `defaultConnected` to `mock` https://github.com/wevm/wagmi/commit/b8768c07b54353a65697df08b87657dcb1e4d24e

```ts
const config = createConfig({
  connectors: [
    mock({
      accounts,
      features: {
        defaultConnected: true,
        reconnect: true,
      },
    })
  ],
})
```
